# app.py
from flask import Flask, render_template, request, jsonify
import networkx as nx
from module import (find_optimal_route, create_route_map, load_data,
                    load_city_ids_by_country, get_interpolated_weather,
                    create_loading_route_map, check_route_feasibility)
import folium
import json
import os
import pycountry
import threading
import uuid
import difflib

app = Flask(__name__)


def _normalize_ascii(s):
    """Replace German umlauts with ASCII equivalents for fuzzy city matching."""
    return (s.replace('ä', 'a').replace('ö', 'o').replace('ü', 'u')
             .replace('ß', 'ss'))

# Load your data once at startup
def import_data():
    global city_graph, temperatures, city_names, city_names_ascii
    path = "data/"
    city_graph, temperatures = load_data(path)
    city_names = {}
    for node in city_graph.nodes(data=True):
        city_id = node[0]
        name = node[1].get('name', 'Unknown City')
        city_names[name.lower()] = city_id

    # German city name aliases (generated by build_german_names.py)
    german_names_path = os.path.join(path, 'german_city_names.json')
    german_city_names = {}
    if os.path.exists(german_names_path):
        with open(german_names_path, encoding='utf-8') as f:
            german_city_names = json.load(f)
        # Merge into city_names so /search and /calculate both work transparently.
        # Convert int→str to match graph node ID type.
        for de_name, city_id in german_city_names.items():
            if de_name not in city_names:   # don't overwrite English entries
                city_names[de_name] = str(city_id)

    # Build ASCII-normalized index for umlaut-tolerant lookups (first key wins)
    city_names_ascii = {}
    for k in city_names:
        ascii_k = _normalize_ascii(k)
        if ascii_k not in city_names_ascii:
            city_names_ascii[ascii_k] = k

import_data()


def resolve_city_name(raw):
    """Resolve a raw user input to (city_id, matched_key).

    Tries in order:
      1. Strip whitespace + exact lowercase match
      2. ASCII-normalised match  (Koln → köln, Dusseldorf → düsseldorf)
      3. difflib fuzzy match on ASCII-normalised names (muenchen → münchen)
    Returns (None, None) when no match is found.
    """
    name = raw.strip().lower()
    if not name:
        return None, None
    # 1. Exact
    if name in city_names:
        return city_names[name], name
    # 2. ASCII-normalised (strip umlauts from both sides)
    ascii_name = _normalize_ascii(name)
    if ascii_name in city_names_ascii:
        orig_key = city_names_ascii[ascii_name]
        return city_names[orig_key], orig_key
    # 3. Fuzzy on ASCII-normalised names (handles ue→ü, typos, etc.)
    matches = difflib.get_close_matches(ascii_name, city_names_ascii.keys(), n=1, cutoff=0.82)
    if matches:
        orig_key = city_names_ascii[matches[0]]
        return city_names[orig_key], orig_key
    return None, None

# In-memory job store (safe with gthread workers – single process)
jobs = {}


@app.route('/')
def index():
    return render_template('index.html')

@app.route('/search')
def search_cities():
    query = request.args.get('term', '').lower()
    matches = [name for name in city_names.keys() if query in name]
    return jsonify(matches[:10])

@app.route('/search_countries')
def search_countries():
    query = request.args.get('term', '').lower()
    countries = [c.name for c in pycountry.countries]
    matches = [c for c in countries if query in c.lower()]
    return jsonify(matches[:10])


def build_route_weather_json(graph, temperatures, route, start_day, warming_factor=0.0):
    """
    Berechnet Wetterdaten für jeden Stadt-Stop auf der Route
    für einen Puffer von ±70 Tagen um den Starttag.
    """
    all_start_days = [((start_day + offset - 1 + 365) % 365) + 1
                      for offset in range(-70, 71)]

    result = []
    for city_id, abs_day, city_name, distance in route:
        rel_day = abs_day - route[0][1]

        weather_by_startday = {}
        for sd in all_start_days:
            cal_day = ((sd + rel_day - 1) % 365) + 1
            try:
                w = get_interpolated_weather(city_id, cal_day, temperatures, warming_factor)
                weather_by_startday[str(sd)] = [
                    round(v, 2) if v is not None else None
                    for v in w
                ]
            except Exception:
                weather_by_startday[str(sd)] = [None] * 6

        result.append({
            "city_name":           city_name,
            "rel_day":             rel_day,
            "weather_by_startday": weather_by_startday,
        })

    return json.dumps(result)


# ---------------------------------------------------------------------------
# Background calculation thread
# ---------------------------------------------------------------------------

def run_calculation(job_id, params):
    job = jobs[job_id]

    def update(step, message, **kwargs):
        job['step'] = step
        job['message'] = message
        for k, v in kwargs.items():
            job[k] = v

    try:
        update(1, "Routenalgorithmus läuft...")

        city_ids_by_country = load_city_ids_by_country('data/city_ids_by_country.json')

        # ── Fast feasibility pre-check (uses a graph copy, does not mutate global) ──
        feasibility_issues = check_route_feasibility(
            city_graph,
            target_cities=params['city_ids'],
            start_city=params['start_city'],
            connections=params['connections'],
            blocked_countries=params['blocked_countries'],
            city_ids_by_country=city_ids_by_country,
        )
        if feasibility_issues:
            issue_text = ' | '.join(feasibility_issues)
            job['status'] = 'error'
            job['error'] = issue_text
            job['message'] = 'Städte nicht erreichbar'
            return

        route, start_day, fail_reason = find_optimal_route(
            city_graph,
            params['blocked_countries'],
            city_ids_by_country,
            temperatures,
            target_cities=params['city_ids'],
            start_city=params['start_city'],
            connections=params['connections'],
            start_day=params['start_day'],
            desired_low_temp=params['low_temp'],
            desired_high_temp=params['high_temp'],
            temp_weight=params['temp_weight'],
            auto_threshold_percentile=10,
            exp=2,
            low_temp_range=(params['low_temp_min'], params['low_temp_max']),
            high_temp_range=(params['high_temp_min'], params['high_temp_max']),
            daily_max_km=params['daily_km'],
            max_days=params['max_days'],
            sorted_input=params['sorted_input'],
            city_rest_days=params['city_rest_days'],
            warming_factor=params['warming_factor'],
        )

        if not route:
            job['status'] = 'error'
            job['error'] = fail_reason or 'Kein gültiger Routenverlauf gefunden.'
            job['message'] = 'Keine Route gefunden'
            return

        # Build rough map data (straight lines, no OSRM) and show immediately
        rough_map = create_loading_route_map(
            city_graph, temperatures, route, 2,
            params['low_temp'], params['high_temp'],
            params['low_temp_min'], params['low_temp_max'],
            params['high_temp_min'], params['high_temp_max'],
            warming_factor=params['warming_factor'],
        )
        update(2, "Route gefunden! Straßenverlauf wird geladen...",
               status='route_found', rough_map=rough_map,
               osrm_done=0, osrm_total=max(0, len(route) - 1))

        # OSRM progress counter (cumulative across all sub-routes)
        osrm_counter = [0]
        total_est = max(1, len(route) - 1)

        def osrm_progress(done_in_sub, total_in_sub):
            osrm_counter[0] += 1
            job['osrm_done'] = osrm_counter[0]
            job['osrm_total'] = max(osrm_counter[0], total_est)
            job['message'] = (f"Straßen: {osrm_counter[0]}/"
                              f"{job['osrm_total']} Segmente geladen")

        route_map, elevation_svg, osrm_distances = create_route_map(
            city_graph, temperatures, route, 2,
            params['low_temp'], params['high_temp'],
            params['low_temp_min'], params['low_temp_max'],
            params['high_temp_min'], params['high_temp_max'],
            connections=params['connections'],
            show_elevation=True,
            routing_mode=params['routing_mode'],
            elev_points_per_1000km=params['elev_points_per_1000km'],
            progress_callback=osrm_progress,
            warming_factor=params['warming_factor'],
        )

        update(3, "Höhenprofil wird erstellt...", status='running')

        overall_distance = sum(d for d in osrm_distances if d > 0)
        route_with_osrm = [
            (city_id, day, city_name, osrm_distances[i] if i < len(osrm_distances) else 0)
            for i, (city_id, day, city_name, _) in enumerate(route)
        ]
        route_weather_json = build_route_weather_json(
            city_graph, temperatures, route, start_day,
            warming_factor=params['warming_factor'],
        )

        job['result'] = {
            'map_html':          route_map._repr_html_(),
            'elevation_svg':     elevation_svg,
            'route_weather_json': route_weather_json,
            'route':             route_with_osrm,
            'start_day':         start_day,
            'overall_distance':  overall_distance,
            'desired_low_temp':  params['low_temp'],
            'desired_high_temp': params['high_temp'],
            'city_rest_days':    params['city_rest_days'],
        }
        update(3, "Fertig!", status='done')

    except Exception as e:
        import traceback
        traceback.print_exc()
        job['status'] = 'error'
        job['error'] = str(e)
        job['message'] = f"Fehler: {e}"


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.route('/calculate', methods=['POST'])
def calculate_route():
    # Parse form data
    cities = request.form.getlist('cities')
    start_city_name = request.form.get('start_city', '')
    connection_starts = request.form.getlist('connection_start')
    connection_stops = request.form.getlist('connection_stop')

    start_day_raw = request.form.get('start_day', '').strip()
    start_day = int(start_day_raw) if start_day_raw else None

    high_temp = float(request.form.get('high_temp', 25))
    low_temp  = float(request.form.get('low_temp', 15))

    high_temp_min = request.form.get('high_temp_min', '').strip()
    high_temp_min = float(high_temp_min) if high_temp_min else float('-inf')

    high_temp_max = request.form.get('high_temp_max', '').strip()
    high_temp_max = float(high_temp_max) if high_temp_max else float('inf')

    low_temp_min = request.form.get('low_temp_min', '').strip()
    low_temp_min = float(low_temp_min) if low_temp_min else float('-inf')

    low_temp_max = request.form.get('low_temp_max', '').strip()
    low_temp_max = float(low_temp_max) if low_temp_max else float('inf')

    daily_km  = float(request.form.get('daily_km', 100))
    max_days  = int(request.form.get('max_days', 30))
    elev_points_per_1000km = int(request.form.get('elev_points_per_1000km', 1000))
    temp_weight = float(request.form.get('temp_weight', 0.5))
    warming_factor = float(request.form.get('warming_factor', 0.6))

    routing_mode = request.form.get('routing_mode', 'car')
    if routing_mode not in ('car', 'bicycle', 'car_no_highway'):
        routing_mode = 'car'

    sorted_input = request.form.get('sorted_input') == 'true'

    blocked_countries = request.form.getlist('blocked_countries')
    additional_blocked = request.form.getlist('additional_blocked_countries')
    country_map = {c.name: c.alpha_2 for c in pycountry.countries}
    for name in additional_blocked:
        code = country_map.get(name)
        if code:
            blocked_countries.append(code)

    city_rest_days_raw = request.form.getlist('city_rest_days')

    # Resolve each city name with fuzzy/umlaut-tolerant matching
    resolved_cities = []   # [(original_stripped, city_id, matched_key)]
    for city in cities:
        city_id, matched_key = resolve_city_name(city)
        resolved_cities.append((city.strip(), city_id, matched_key))

    city_ids = []
    city_rest_days = {}
    for i, (orig, city_id, matched_key) in enumerate(resolved_cities):
        if city_id is not None:
            city_ids.append(city_id)
            try:
                rest = int(city_rest_days_raw[i]) if i < len(city_rest_days_raw) else 0
            except (ValueError, TypeError):
                rest = 0
            if rest > 0:
                city_rest_days[city_id] = rest

    connections = []
    for start, stop in zip(connection_starts, connection_stops):
        s_id, s_key = resolve_city_name(start)
        e_id, e_key = resolve_city_name(stop)
        if s_id is not None and e_id is not None:
            connections.append((s_id, e_id))

    start_city, start_matched_key = resolve_city_name(start_city_name)

    print("Connections:", connections)
    print("start city:", start_city)
    print("cities:", city_ids)
    print("sorted_input:", sorted_input)
    print(blocked_countries)

    # ── Server-side validation ───────────────────────────────────────────
    unrecognized = [orig for orig, city_id, _ in resolved_cities
                    if city_id is None and orig]
    corrections  = [(orig, matched_key) for orig, city_id, matched_key in resolved_cities
                    if city_id is not None and orig.lower() != matched_key]
    validation_errors = []
    warnings = []

    if not city_ids and not start_city:
        if unrecognized:
            validation_errors.append(
                f'Keine Städte erkannt. Nicht gefundene Städte: {", ".join(unrecognized)}. '
                f'Bitte Schreibweise prüfen (Autocomplete verwenden).'
            )
        else:
            validation_errors.append('Bitte mindestens eine Stadt eingeben.')

    if unrecognized and city_ids:
        validation_errors.append(
            f'Folgende Städte wurden nicht gefunden und werden übersprungen: '
            f'{", ".join(unrecognized)}.'
        )

    if corrections:
        warnings.append(
            'Eingaben automatisch korrigiert: '
            + ', '.join(f'„{orig}" → „{key}"' for orig, key in corrections)
        )

    if start_city_name and not start_city:
        validation_errors.append(
            f'Startstadt „{start_city_name}" nicht gefunden. Bitte Schreibweise prüfen.'
        )
    elif start_city_name and start_matched_key and start_city_name.strip().lower() != start_matched_key:
        warnings.append(f'Startstadt „{start_city_name.strip()}" als „{start_matched_key}" erkannt.')

    if low_temp > high_temp:
        validation_errors.append(
            f'Nachttemperatur ({low_temp:.1f}°C) darf nicht höher sein als '
            f'Tagestemperatur ({high_temp:.1f}°C).'
        )

    if (high_temp_min != float('-inf') and high_temp_max != float('inf')
            and high_temp_min > high_temp_max):
        validation_errors.append(
            f'Tagestemperatur Bereich: Min ({high_temp_min:.1f}°C) ist größer als '
            f'Max ({high_temp_max:.1f}°C).'
        )

    if (low_temp_min != float('-inf') and low_temp_max != float('inf')
            and low_temp_min > low_temp_max):
        validation_errors.append(
            f'Nachttemperatur Bereich: Min ({low_temp_min:.1f}°C) ist größer als '
            f'Max ({low_temp_max:.1f}°C).'
        )

    if daily_km < 1:
        validation_errors.append('Max. Tagesstrecke muss mindestens 1 km betragen.')

    if max_days < 1:
        validation_errors.append('Max. Reisetage muss mindestens 1 betragen.')

    # Connections: flag pairs where only one side was recognized
    for start, stop in zip(connection_starts, connection_stops):
        if start.strip() and stop.strip():
            s_id, _ = resolve_city_name(start)
            e_id, _ = resolve_city_name(stop)
            if s_id is None and e_id is None:
                validation_errors.append(
                    f'Verbindung „{start} → {stop}": Beide Städte nicht gefunden.'
                )
            elif s_id is None:
                validation_errors.append(
                    f'Verbindung: Startstadt „{start}" nicht gefunden.'
                )
            elif e_id is None:
                validation_errors.append(
                    f'Verbindung: Zielstadt „{stop}" nicht gefunden.'
                )

    # "übersprungen" messages are non-blocking warnings, everything else blocks
    blocking = [e for e in validation_errors if 'übersprungen' not in e]
    skip_warnings = [e for e in validation_errors if 'übersprungen' in e]
    all_warnings = skip_warnings + warnings
    if blocking:
        return render_template('error.html',
                               errors=blocking,
                               warnings=all_warnings)

    params = dict(
        city_ids=city_ids,
        start_city=start_city,
        connections=connections,
        start_day=start_day,
        low_temp=low_temp,
        high_temp=high_temp,
        high_temp_min=high_temp_min,
        high_temp_max=high_temp_max,
        low_temp_min=low_temp_min,
        low_temp_max=low_temp_max,
        daily_km=daily_km,
        max_days=max_days,
        elev_points_per_1000km=elev_points_per_1000km,
        temp_weight=temp_weight,
        warming_factor=warming_factor,
        routing_mode=routing_mode,
        sorted_input=sorted_input,
        blocked_countries=blocked_countries,
        city_rest_days=city_rest_days,
    )

    job_id = str(uuid.uuid4())
    jobs[job_id] = {
        'status':     'starting',
        'step':       1,
        'message':    'Starte Berechnung...',
        'osrm_done':  0,
        'osrm_total': 0,
        'rough_map':  None,
        'result':     None,
        'error':      None,
    }

    t = threading.Thread(target=run_calculation, args=(job_id, params), daemon=True)
    t.start()

    return render_template('loading.html', job_id=job_id)


@app.route('/status/<job_id>')
def job_status(job_id):
    job = jobs.get(job_id)
    if not job:
        return jsonify({'status': 'error', 'error': 'Job nicht gefunden'})
    return jsonify({
        'status':     job['status'],
        'step':       job['step'],
        'message':    job['message'],
        'osrm_done':  job['osrm_done'],
        'osrm_total': job['osrm_total'],
        'rough_map':  job['rough_map'],
        'error':      job.get('error'),
    })


@app.route('/result/<job_id>')
def job_result(job_id):
    job = jobs.get(job_id)
    if not job or job['status'] != 'done' or not job.get('result'):
        return render_template('error.html', message="Ergebnis nicht verfügbar")
    r = job['result']
    return render_template('results.html',
                           map_html=r['map_html'],
                           elevation_svg=r['elevation_svg'],
                           route_weather_json=r['route_weather_json'],
                           route=r['route'],
                           start_day=r['start_day'],
                           overall_distance=r['overall_distance'],
                           desired_low_temp=r['desired_low_temp'],
                           desired_high_temp=r['desired_high_temp'],
                           city_rest_days=r['city_rest_days'])


if __name__ == '__main__':
    app.run(debug=True)
